# Generated by Django 5.2.12 on 2026-03-14 13:25

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, help_text='Tenant isolation. NULL = platform-global knowledge.', null=True)),
                ('outline_id', models.UUIDField(db_index=True, help_text='Outline document UUID (from webhook payload).', unique=True)),
                ('outline_url', models.URLField(blank=True, max_length=500)),
                ('collection_id', models.UUIDField(blank=True, help_text='Outline collection UUID.', null=True)),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField(help_text='Full Markdown content from Outline.')),
                ('category', models.CharField(choices=[('runbook', 'Runbook'), ('concept', 'Architektur-Konzept'), ('lesson', 'Lesson Learned'), ('adr_draft', 'ADR-Draft'), ('hub_doc', 'Hub-Dokumentation'), ('adr_mirror', 'ADR (Read-Only Mirror)')], db_index=True, default='runbook', max_length=20)),
                ('related_adr_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Referenced ADR numbers, e.g. [142, 143, 145].', size=None)),
                ('related_hubs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="Hub names, e.g. ['research-hub', 'risk-hub'].", size=None)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary.')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='AI-extracted keywords.', size=None)),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pending'), ('enriched', 'Enriched'), ('failed', 'Failed'), ('stale', 'Stale (>24h)')], default='pending', max_length=20)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('outline_updated_at', models.DateTimeField(blank=True, help_text='Last update timestamp from Outline.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['category'], name='idx_knowledge_category'), models.Index(fields=['tenant_id'], name='idx_knowledge_tenant'), models.Index(fields=['enrichment_status'], name='idx_knowledge_enrichment')],
                'constraints': [models.UniqueConstraint(fields=('outline_id',), name='unique_knowledge_outline_id')],
            },
        ),
    ]
