# Generated by Django 5.2.12 on 2026-03-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='content_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of title+text for change detection.', max_length=64),
        ),
    ]
