# Generated by Django 5.2.12 on 2026-03-13 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, default=1, help_text='PLATFORM_INTERNAL_TENANT_ID (1) for internal doc-hub', verbose_name='Tenant ID')),
                ('paperless_document_id', models.IntegerField(db_index=True, verbose_name='Paperless Document ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('correspondent', models.CharField(blank=True, default='', max_length=255, verbose_name='Correspondent')),
                ('paperless_url', models.URLField(blank=True, verbose_name='Paperless URL')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('status', models.CharField(choices=[('pending', 'Pending OCR'), ('indexed', 'Indexed'), ('enriched', 'AI-Enriched'), ('error', 'Error')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('contract', 'Contract'), ('receipt', 'Receipt'), ('license', 'License / Certificate'), ('correspondence', 'Correspondence'), ('other', 'Other')], db_index=True, default='other', max_length=30, verbose_name='Document Type')),
                ('document_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI Summary')),
                ('ai_keywords', models.JSONField(blank=True, default=list, verbose_name='AI Keywords')),
                ('ai_enriched_at', models.DateTimeField(blank=True, null=True, verbose_name='AI Enriched At')),
                ('paperless_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Paperless Update')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Document Metadata',
                'verbose_name_plural': 'Document Metadata',
                'ordering': ['-document_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('paperless_document_id',), name='uq_document_metadata_paperless_id_active')],
            },
        ),
    ]
