# Generated by Django 5.1.15 on 2026-03-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='academic_sources',
            field=models.JSONField(default=list, help_text='Akademische Quellen (arxiv, semantic_scholar, pubmed, openalex)'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='depth',
            field=models.CharField(choices=[('quick', 'Schnell (5 Quellen)'), ('standard', 'Standard (15 Quellen)'), ('deep', 'Tief (30 Quellen)'), ('exhaustive', 'Exhaustiv (50 Quellen)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='language',
            field=models.CharField(default='de', max_length=10),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='research_type',
            field=models.CharField(choices=[('web', 'Web-Recherche'), ('academic', 'Wissenschaftlich'), ('combined', 'Kombiniert (Web + Wissenschaft)'), ('fact_check', 'Faktencheck')], default='combined', max_length=20),
        ),
    ]
