# Generated by Django 5.2.6 on 2026-03-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_add_tenant_id_to_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='use_deep_analysis',
            field=models.BooleanField(default=False, help_text='2-Stufen: Erst Llama-Zusammenfassung, dann OpenAI-Tiefenanalyse.'),
        ),
        migrations.AddField(
            model_name='researchresult',
            name='deep_analysis',
            field=models.TextField(blank=True, help_text='Tiefenanalyse durch OpenAI (Stufe 2).'),
        ),
        migrations.AddField(
            model_name='researchresult',
            name='deep_analysis_model',
            field=models.CharField(blank=True, help_text='Modell für die Tiefenanalyse, z.B. gpt-4.1', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('analysing', 'Analysing'), ('done', 'Done'), ('error', 'Error')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
