# Generated by Django 5.1.15 on 2026-06-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_deep_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchresult',
            name='run_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Idempotency key per research run (Celery task id) — dedupes retries.', max_length=64),
        ),
    ]
